name: Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup SSH Keys and known_hosts
        run: |
            echo "${{ secrets.SSH_KEY }}" > id_rsa

      - name: Docker Build
        uses: benjlevesque/actions-docker-gcr/build@v1.1
        with:
          image: ${{ GOOGLE_PROJECT_ID }}/pgm
          tag: master

      - name: Docker Push
        uses: benjlevesque/actions-docker-gcr/push@v1.1
        with:
          gcloud_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
          image: ${{ GOOGLE_PROJECT_ID }}/pgm
          tag: master