name: Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup SSH Keys and known_hosts
        run: |
            echo "${{ secrets.SSH_KEY }}" > id_rsa

      - name: Docker Build
        uses: raccoondev/push-docker-gcr
        with:
          gcr_host: gcr.io
          image_name: pgm
          image_tag: ${{ GITHUB_REF }}
          env:
            GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
            GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}