name: Docker

on:
  push:
    branches:
      - master 
  pull_request:
  repository_dispatch:
    types:
      - build

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1

      - name: Set up Maven
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v9
        with:
          repositories: '[{ "id": "bolt-rip-private", "url": "https://repo.repsy.io/mvn/boltrip/private", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } }]'
          servers: '[{ "id": "bolt-rip-private", "username": "${{ secrets.MAVEN_USERNAME }}", "password": "${{ secrets.MAVEN_PASSWORD }}" }]'

      - name: Download private plugins from repsy
        run: |
            #mvn dependency:get -DrepoUrl=https://repo.repsy.io/mvn/boltrip/private -Dartifact=org.anchor:Nettle:1.0.0-SNAPSHOT -Ddest=plugins/
            mvn dependency:get -DrepoUrl=https://repo.repsy.io/mvn/boltrip/private -Dartifact=me.pablete1234:bacperms:1.2.2 -Ddest=plugins/

      - name: Setup SSH Keys and known_hosts
        run: |
            echo "${{ secrets.SSH_KEY_MAPS_PGM }}" > id_rsa_maps_pgm

      - name: Login to GitHub Docker Registry
        run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.GHR_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GHR_PASSWORD }}

      - name: Publish to Registry
        uses: docker://docker.pkg.github.com/elgohr/publish-docker-github-action/publish-docker-github-action:latest
        with:
          name: bolt-rip/config-pgm
          registry: ghcr.io
          username: ${{ secrets.GHR_USERNAME }}
          password: ${{ secrets.GHR_PASSWORD }}
          snapshot: true
